### ISSUE TITLE
Paclet Server Integration

### ISSUE THREAD

**Issue by b3m2a1** [cklausme/EcoEvo#1]
I was wondering if you'd want to add your package to the [Paclet Server / Package Repo)](https://paclets.github.io/PacletServer/) I've set up for the general Mathematica community. Per [this](https://github.com/paclets/PacletServer/issues/35) I'm trying to increase awareness and get more paclets on the server so that more people can benefit from it.

I can handle any initial reformatting necessary to make everything work right, and I'll submit a pull request with any changes.

**Comment by cklausme** [comment]
Hey b3m2a1, thanks for writing.  If it doesn't require much input from me, please feel free to add my humble paclet.  It's still a work in progress, but what isn't?

thanks!  Chris
--
Christopher Klausmeier
Kellogg Biological Station &
Department of Plant Biology
Michigan State University
Hickory Corners MI 49060

Phone: (269) 671-4330
Web: http://preston.kbs.msu.edu/
Email: klausme1@msu.edu

**Comment by b3m2a1** [comment]
Sounds good. I'll see if I need to add anything to get it on the server and if not I'll point it to your repo here. If so I'll submit a pull request with the necessary changes before doing so.

**Comment by b3m2a1** [comment]
[Merged](https://paclets.github.io/PacletServer/ecoevo.html). When you have updates, make an issue on the paclet server repo (see what Szabolcs has done for instance). I'll make sure it enters the next build.

**Comment by cklausme** [comment]
Great, thanks!
--
Christopher Klausmeier
Kellogg Biological Station &
Department of Plant Biology
Michigan State University
Hickory Corners MI 49060

Phone: (269) 671-4330
Web: http://preston.kbs.msu.edu/
Email: klausme1@msu.edu
